"""Add Brand model

Revision ID: 0967f596293b
Revises: 
Create Date: 2025-11-05 18:14:05.053064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0967f596293b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_products_brand_id', 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_products_brand_id', type_='foreignkey')
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###