"""Add count column to products table

Revision ID: 170cce6407f9
Revises: 0967f596293b
Create Date: 2025-11-05 18:38:37.806984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170cce6407f9'
down_revision = '0967f596293b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE products SET count = 0 WHERE count IS NULL")
    
    # Make the column NOT NULL
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('count', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###