"""Add custom_id and delivery agent fields to users table

Revision ID: aecd91c031c0
Revises: 170cce6407f9
Create Date: 2025-11-30 15:10:43.436480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecd91c031c0'
down_revision = '170cce6407f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cover_letter', sa.Text(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_users_custom_id', ['custom_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_custom_id', type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('cover_letter')
        batch_op.drop_column('availability')
        batch_op.drop_column('experience')
        batch_op.drop_column('custom_id')

    # ### end Alembic commands ###
