"""add has_rated to orders

Revision ID: dbcd8ec827d7
Revises: aecd91c031c0
Create Date: 2026-03-09 16:57:41.602707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbcd8ec827d7'
down_revision = 'aecd91c031c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_rated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('has_rated')

    # ### end Alembic commands ###
